### ISSUE TITLE
u forgot add file in linux folder

### ISSUE THREAD

**Issue by n1rdeks** [binarybottle/engram-es#39]
/engram-es/keymaps/linux/ is empty 

(interesting, how  u add layer with AltG and, maybe, Level5).

P.S. This layout better, than Dvorak? I use HHKB, but planning 40% something, maybe Corne... And please, add to your site roadmap or something. How about Russian lang with your approach? IMO, this is amazing theme, set punctuation in center.

**Comment by binarybottle** [comment]
Thank you for your interest!  The installation folders are currently empty because I am waiting on my colleagues who have successfully installed on different platforms to submit a pull request.

**Comment by n1rdeks** [comment]
oh. Ok. Thanks. U w8  this guy? @sunaku?

And how create something about DVP? But on this time i don't need this mode, because I use AltG for layer (all numbers and symbols) and rmenu/rctrl for level5 (arrows, volumes, F1-12 etc). 

And again. If i learn this keyboard layout, u submit her (engram) in Xorg(Wayland)? Workman and Colemak added... (But, IMHO, Dvorak better ;))

**Comment by n1rdeks** [comment]
With DVP => engram - I can help. For programmers ;)
